# 환경 프로필 변경방법
# 오른쪽 위 클릭 후 Edit configuration... 클릭 > Active profiles에 dev, create, deploy 중 하나 입력

spring:
  application.name: WouldYouIn

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    default: dev

  # 소셜로그인 테스트시 캐시 비활성화
  thymeleaf:
    cache: false

  # devtools 자동 빌드 해제
  devtools:
    restart:
      enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true

# log4j log level setting
logging.level.org.ktc2.cokaen.wouldyouin: debug

# for image storage path
image:
  api-url: ${SERVER_DOMAIN_NAME}/api/images
  upload:
    parent-path: ${IMAGE_UPLOAD_PATH}
    curation:
      child-path: curation
    member:
      child-path: member
    event:
      child-path: event
    ad:
      child-path: advertisement

# for jwt
jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: 86400000 # 1day

# for social login
oauth:
  kakao:
    uri:
      login:
        host: kauth.kakao.com
        path: /oauth/token
      access:
        host: kapi.kakao.com
        path: /v2/user/me
    client:
      id: ${KAKAO_CLIENT_ID}
      secret: ${KAKAO_CLIENT_SECRET}
    redirect_uri: ${SERVER_DOMAIN_NAME}/api/auth/social/redirect/kakao
  google:
    uri:
      login:
        host: oauth2.googleapis.com
        path: /token
      access:
        host: www.googleapis.com
        path: /userinfo/v2/me
    client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET}
    redirect_uri: ${SERVER_DOMAIN_NAME}/api/auth/social/redirect/google
    scope:
      - email
      - profile
  payment:
    "approval_url": ${SERVER_DOMAIN_NAME}/api/events
    "cancel_url": ${SERVER_DOMAIN_NAME}/api/events
    "fail_url": ${SERVER_DOMAIN_NAME}/api/events
    "secret_key": ${KAKAOPAY_SECRET_KEY}
    "kakao_pay_single_payment_url": online/v1/payment/ready
    "kakao-pay-request-host": https://open-api.kakaopay.com