#server settings
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: deploy
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATASOURCE_URL}?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul